GET http://localhost:3000/users

###

POST http://localhost:3000/appointments
Content-Type: application/json

{
  "title": "blut",
  "date": "2023-01-01",
  "time": "10:10",
  "insurance": "privat",
  "user": "maticmar",
  "name": "Marcel Matic"
}
###

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "a",
  "role": "admin",
  "password": "a"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "maticmar",
  "password": "admin"
}

###

DELETE http://localhost:3000/appointments/6402152e153401bbfcae2a76

###

PATCH http://localhost:3000/appointments/6400a33f1c3138d80c35a9f6
Content-Type: application/json

{
  "title": "NEUER TITEL"
}

###

GET http://localhost:3000/users/NEWUSER