GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "maticmar",
  "password": "admin",
  "role": "admin"
}
###

GET http://localhost:3000/appointments/maticmar

